---
- name: Configure log rotation
  template:
    src: logrotate.conf.j2
    dest: /etc/logrotate.d/mongodb.conf
  when: mongo_logrotate

###based on https://docs.mongodb.com/v3.4/tutorial/deploy-replica-set-with-keyfile-access-control/

- name: Configure mongodb
  template:
    src: mongod.conf.j2
    dest: /etc/mongod.conf
notify: restart mongod

- name: create mongod admin user
  mongodb_user:
    database: admin
    name: "{{ mongo_admin_user }}"
    replica_set: "{{ mongo_replset_name }}"
    password: "{{ mongo_admin_password }}"
    roles: readWriteAnyDatabase,clusterAdmin,dbAdminAnyDatabase
    state: present


