---
- name: 'Configuring MongoDB repository'
  yum_repository:
    name: mongodb-org-3.4
    description: MongoDB Repository
    baseurl: https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/3.4/x86_64/
    gpgcheck: yes
    gpgkey: https://www.mongodb.org/static/pgp/server-3.4.asc
    enabled: yes
  
- name: 'Installing MongoDB package'
  yum: 
    name: "{{ item }}"
    state: installed 
    update_cache: yes
  with_items:
    - mongodb-org
 
- name: 'Installing pymongo'
  pip:
    name: pymongo
  
- name: 'Configuring MongoDB service'
  systemd: name=mongod daemon_reload=yes enabled=yes
 
- name: 'Creating MongoDB directories'
  file: 
    path: "{{ item }}"
    state: directory
    owner: mongod 
    group: mongod
    recurse: yes
  with_items:
    - "{{ mongo_data_path }}"
    - "{{ mongo_log_path }}"
    
- name: 'adding dbpath'
  lineinfile: 
    dest: /etc/mongod.conf
    state: present
    regexp: '^  dbPath:'
    line: '  dbPath: {{ mongo_data_path }}'

- name: 'adding log_path'
  lineinfile:
    dest: /etc/mongod.conf
    state: present 
    regexp: '^  path:' 
    line: '  path: {{ mongo_log_path }}/mongodb.log'

- name: 'Configuring the replset'
  blockinfile:
    dest: /etc/mongod.conf
    state: present
    block: |
      replication:
         replSetName: "{{ mongo_replset_name }}"

- name: 'Configuring binding'
  lineinfile:
    dest: /etc/mongod.conf
    state: present
    regexp: '^  bindIp'
    line: '  bindIp: 0.0.0.0'
  notify:
    - restart mongod
  
- name: starting service mongod
  service:
    name: mongod
    state: started

- name: update /etc/hosts with hostname
  lineinfile:
    dest: /etc/hosts
    state: present
    insertbefore: BOF
    regexp: '^127.0.0.1'
    line: "127.0.0.1 localhost {{ ansible_hostname }}"

- name: update /etc/hosts with cluster hostnames
  lineinfile:
    dest: /etc/hosts
    state: present
    insertafter: EOF
    line: "{{ hostvars[item]['ansible_all_ipv4_addresses']|first }} {{ hostvars[item]['ansible_hostname'] }}"
  with_items: 
    - "{{ mongo_cluster_members }}"
